version: '3.9' # optional since v1.27.0
services:
  api:
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - './mongo/data:/data/db'
    ports:
      - '27017:27017'
