version: '3.9' # optional since v1.27.0
services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    volumes:
      - './packages/api:/usr/src/app'
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - './mongo/data:/data/db'
    ports:
      - '27017:27017'
