version: '3.9' # optional since v1.27.0
services:
  api1:
    build: ./api
    volumes:
      - './api:/usr/src/app'
    ports:
      - '4001:4000'
    depends_on:
      mongo: 
          condition: service_healthy
    restart: always

  api2:
    build: ./api
    volumes:
      - './api:/usr/src/app'
    ports:
      - '4002:4000'
    depends_on:
      mongo: 
          condition: service_healthy
    restart: always
  
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4000:80
    depends_on:
      - api1 
      - api2 


  write-service:
    build: ./write-service
    volumes:
      - './write-service:/usr/src/app'
    depends_on:
      mongo: 
          condition: service_healthy
    restart: always

  mongo:
    image: mongo:4.0
    volumes:
      - './mongo/data:/data/db'
    ports:
      - '27017:27017'
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/book --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s 

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: -1
    restart: always
    healthcheck:
      test: ["CMD", ...]
      interval: 30s
      timeout: 10s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: 'no'
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
    depends_on:
      - kafka
    restart: always

